### PR TITLE
Add a PR template for docs

### PR DESCRIPTION
**Pull request by AartiKriplani**

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks, @AartiKriplani.

**Comment by RichardJJG** [comment]
Hi, @AartiKriplani. Is this file going to become a guide for best practice for engineers submitting PRs to docs-rmq-k8s? If so, might this information be better placed in the README instead of as a standalone file?

**Comment by AartiKriplani** [comment]
@RichardJJG : This is a template that should be automatically used when somebody creates a new PR for this repo according to [Github documentation ](https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository). 
We decided to have this because this question of adding it to the release branch came up several times before.

**Comment by RichardJJG** [comment]
@AartiKriplani, thanks, sounds useful! I've merged it back into master.

**Pull request merged**
